# Copyright (C) 2020 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ActionOpenDocument:
    name: ActionOpenDocument
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: ActionOpenDocument
        run: ./gradlew assembleDebug

  ActionOpenDocumentTree:
    name: ActionOpenDocumentTree
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: ActionOpenDocumentTree
        run: ./gradlew assembleDebug

  ContentProviderPaging:
    name: ContentProviderPaging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: ContentProviderPaging
        run: ./gradlew assembleDebug

  ContentProviderPagingKotlin:
    name: ContentProviderPagingKotlin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: ContentProviderPagingKotlin
        run: ./gradlew assembleDebug

  FileManager:
    name: FileManager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: FileManager
        run: ./gradlew assembleDebug

  FileProvider:
    name: FileProvider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: FileProvider
        run: ./gradlew assembleDebug

  MediaStore:
    name: MediaStore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: MediaStore
        run: ./gradlew assembleDebug

  SafDemos:
    name: SafDemos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: SafDemos
        run: ./gradlew assembleDebug

  ScopedStorage:
    name: ScopedStorage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: ScopedStorage
        run: ./gradlew assembleDebug

  SharingShortcuts:
    name: SharingShortcuts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: SharingShortcuts
        run: ./gradlew assembleDebug

  StorageClient:
    name: StorageClient
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: StorageClient
        run: ./gradlew assembleDebug

  StorageProvider:
    name: StorageProvider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: StorageProvider
        run: ./gradlew assembleDebug
