# Copyright (C) 2020 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ActionOpenDocument:
    name: ActionOpenDocument
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: ActionOpenDocument
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ActionOpenDocument-build
          path: ActionOpenDocument/app/build/outputs/

  ActionOpenDocumentTree:
    name: ActionOpenDocumentTree
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: ActionOpenDocumentTree
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ActionOpenDocumentTree-build
          path: ActionOpenDocumentTree/app/build/outputs/

  ContentProviderPaging:
    name: ContentProviderPaging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: ContentProviderPaging
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ContentProviderPaging-build
          path: ContentProviderPaging/app/build/outputs/

  ContentProviderPagingKotlin:
    name: ContentProviderPagingKotlin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: ContentProviderPagingKotlin
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ContentProviderPagingKotlin-build
          path: ContentProviderPagingKotlin/app/build/outputs/

  FileManager:
    name: FileManager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: FileManager
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FileManager-build
          path: FileManager/app/build/outputs/

  FileProvider:
    name: FileProvider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: FileProvider
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FileProvider-build
          path: FileProvider/app/build/outputs/

  MediaStore:
    name: MediaStore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: MediaStore
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MediaStore-build
          path: MediaStore/app/build/outputs/

  SafDemos:
    name: SafDemos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: SafDemos
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SafDemos-build
          path: SafDemos/app/build/outputs/

  ScopedStorage:
    name: ScopedStorage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: ScopedStorage
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ScopedStorage-build
          path: ScopedStorage/app/build/outputs/

  SharingShortcuts:
    name: SharingShortcuts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: SharingShortcuts
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SharingShortcuts-build
          path: SharingShortcuts/Application/build/outputs/

  StorageClient:
    name: StorageClient
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: StorageClient
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StorageClient-build
          path: StorageClient/Application/build/outputs/

  StorageProvider:
    name: StorageProvider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build
        working-directory: StorageProvider
        run: ./gradlew assembleDebug
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StorageProvider-build
          path: StorageProvider/Application/build/outputs/